version: "2.0"
services:
  php:
    build: ./docker
    volumes:
      - ./:/var/www/html
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php

